/**
 * semantics.ts — review semantic layer (metric / grain / joins / filters).
 * Traceability for intents in this module. SQL templates remain in sql.ts;
 * the registry validates plans and FROM/JOIN tables against these defs.
 *
 * Generated by scripts/generate-table-semantics.cjs — edit carefully or re-generate.
 */
import type { SemanticDef } from "@/query-agent/domain/semantics/types";

export const REVIEW_SEMANTICS: Readonly<Record<string, SemanticDef>> = {
  "count_products_with_reviews": {
    "intent": "count_products_with_reviews",
    "entity": "review",
    "metric": "COUNT(*) or distinct count for count_products_with_reviews",
    "grain": "scalar",
    "joins": [
      "productreview",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": []
  },
  "count_products_without_reviews": {
    "intent": "count_products_without_reviews",
    "entity": "review",
    "metric": "COUNT(*) or distinct count for count_products_without_reviews",
    "grain": "scalar",
    "joins": [
      "productreview",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": []
  },
  "count_reviews": {
    "intent": "count_reviews",
    "entity": "review",
    "metric": "COUNT(*) or distinct count for count_reviews",
    "grain": "scalar",
    "joins": [
      "productreview",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": []
  },
  "count_reviews_with_comments": {
    "intent": "count_reviews_with_comments",
    "entity": "review",
    "metric": "COUNT(*) or distinct count for count_reviews_with_comments",
    "grain": "scalar",
    "joins": [
      "productreview",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "hasComments"
    ]
  },
  "count_reviews_without_comments": {
    "intent": "count_reviews_without_comments",
    "entity": "review",
    "metric": "COUNT(*) or distinct count for count_reviews_without_comments",
    "grain": "scalar",
    "joins": [
      "productreview",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "hasComments"
    ]
  },
  "count_distinct_reviewers": {
    "intent": "count_distinct_reviewers",
    "entity": "review",
    "metric": "COUNT(*) or distinct count for count_distinct_reviewers",
    "grain": "scalar",
    "joins": [
      "productreview",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "reviewer",
      "reviewerContains"
    ]
  },
  "count_reviews_by_rating": {
    "intent": "count_reviews_by_rating",
    "entity": "review",
    "metric": "COUNT(*) or distinct count for count_reviews_by_rating",
    "grain": "group_row",
    "joins": [
      "productreview",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "rating",
      "minRating",
      "maxRating"
    ]
  },
  "count_reviews_min_rating": {
    "intent": "count_reviews_min_rating",
    "entity": "review",
    "metric": "COUNT(*) or distinct count for count_reviews_min_rating",
    "grain": "scalar",
    "joins": [
      "productreview",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "rating",
      "minRating",
      "maxRating"
    ]
  },
  "count_reviews_max_rating": {
    "intent": "count_reviews_max_rating",
    "entity": "review",
    "metric": "COUNT(*) or distinct count for count_reviews_max_rating",
    "grain": "scalar",
    "joins": [
      "productreview",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "rating",
      "minRating",
      "maxRating"
    ]
  },
  "count_reviews_for_product": {
    "intent": "count_reviews_for_product",
    "entity": "review",
    "metric": "COUNT(*) or distinct count for count_reviews_for_product",
    "grain": "scalar",
    "joins": [
      "productreview",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "productId",
      "reviewId"
    ]
  },
  "count_reviews_by_reviewer": {
    "intent": "count_reviews_by_reviewer",
    "entity": "review",
    "metric": "COUNT(*) or distinct count for count_reviews_by_reviewer",
    "grain": "group_row",
    "joins": [
      "productreview",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "reviewer",
      "reviewerContains"
    ]
  },
  "count_reviews_by_year": {
    "intent": "count_reviews_by_year",
    "entity": "review",
    "metric": "COUNT(*) or distinct count for count_reviews_by_year",
    "grain": "group_row",
    "joins": [
      "productreview",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "timeField": "productreview.ReviewDate",
    "filtersAllowed": [
      "year",
      "years",
      "startYear",
      "endYear",
      "sellStartYear"
    ]
  },
  "count_reviews_for_category": {
    "intent": "count_reviews_for_category",
    "entity": "review",
    "metric": "COUNT(*) or distinct count for count_reviews_for_category",
    "grain": "scalar",
    "joins": [
      "productreview",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "category"
    ]
  },
  "average_product_rating": {
    "intent": "average_product_rating",
    "entity": "review",
    "metric": "AVG(...) for average_product_rating",
    "grain": "review",
    "joins": [
      "productreview",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "rating",
      "minRating",
      "maxRating"
    ]
  },
  "average_rating_for_product": {
    "intent": "average_rating_for_product",
    "entity": "review",
    "metric": "AVG(...) for average_rating_for_product",
    "grain": "review",
    "joins": [
      "productreview",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "productId",
      "reviewId",
      "rating",
      "minRating",
      "maxRating"
    ]
  },
  "min_product_rating": {
    "intent": "min_product_rating",
    "entity": "review",
    "metric": "MIN(...) for min_product_rating",
    "grain": "scalar",
    "joins": [
      "productreview",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "rating",
      "minRating",
      "maxRating"
    ]
  },
  "max_product_rating": {
    "intent": "max_product_rating",
    "entity": "review",
    "metric": "MAX(...) for max_product_rating",
    "grain": "scalar",
    "joins": [
      "productreview",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "rating",
      "minRating",
      "maxRating"
    ]
  },
  "median_product_rating": {
    "intent": "median_product_rating",
    "entity": "review",
    "metric": "median aggregate for median_product_rating",
    "grain": "scalar",
    "joins": [
      "productreview",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "rating",
      "minRating",
      "maxRating"
    ]
  },
  "sum_review_ratings": {
    "intent": "sum_review_ratings",
    "entity": "review",
    "metric": "SUM(...) for sum_review_ratings",
    "grain": "scalar",
    "joins": [
      "productreview",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "rating",
      "minRating",
      "maxRating"
    ]
  },
  "avg_reviews_per_product": {
    "intent": "avg_reviews_per_product",
    "entity": "review",
    "metric": "AVG(...) for avg_reviews_per_product",
    "grain": "group_row",
    "joins": [
      "productreview",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": []
  },
  "pct_reviews_by_rating": {
    "intent": "pct_reviews_by_rating",
    "entity": "review",
    "metric": "percentage for pct_reviews_by_rating",
    "grain": "group_row",
    "joins": [
      "productreview",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "rating",
      "minRating",
      "maxRating"
    ]
  },
  "variance_product_rating": {
    "intent": "variance_product_rating",
    "entity": "review",
    "metric": "VARIANCE(...) for variance_product_rating",
    "grain": "scalar",
    "joins": [
      "productreview",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "rating",
      "minRating",
      "maxRating"
    ]
  },
  "reviews_by_rating": {
    "intent": "reviews_by_rating",
    "entity": "review",
    "metric": "review attribute / listing",
    "grain": "review",
    "joins": [
      "productreview",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "rating",
      "minRating",
      "maxRating"
    ]
  },
  "avg_rating_by_product": {
    "intent": "avg_rating_by_product",
    "entity": "review",
    "metric": "AVG(...) for avg_rating_by_product",
    "grain": "group_row",
    "joins": [
      "productreview",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "rating",
      "minRating",
      "maxRating"
    ]
  },
  "review_count_by_product": {
    "intent": "review_count_by_product",
    "entity": "review",
    "metric": "review attribute / listing",
    "grain": "review",
    "joins": [
      "productreview",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": []
  },
  "products_highest_avg_rating": {
    "intent": "products_highest_avg_rating",
    "entity": "review",
    "metric": "review attribute / listing",
    "grain": "review",
    "joins": [
      "productreview",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "rating",
      "minRating",
      "maxRating"
    ]
  },
  "products_lowest_avg_rating": {
    "intent": "products_lowest_avg_rating",
    "entity": "review",
    "metric": "review attribute / listing",
    "grain": "review",
    "joins": [
      "productreview",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit",
      "rating",
      "minRating",
      "maxRating"
    ]
  },
  "products_most_reviews": {
    "intent": "products_most_reviews",
    "entity": "review",
    "metric": "review attribute / listing",
    "grain": "review",
    "joins": [
      "productreview",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": []
  },
  "products_fewest_reviews": {
    "intent": "products_fewest_reviews",
    "entity": "review",
    "metric": "review attribute / listing",
    "grain": "review",
    "joins": [
      "productreview",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": []
  },
  "products_with_avg_rating": {
    "intent": "products_with_avg_rating",
    "entity": "review",
    "metric": "review attribute / listing",
    "grain": "review",
    "joins": [
      "productreview",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "rating",
      "minRating",
      "maxRating"
    ]
  },
  "products_only_rating": {
    "intent": "products_only_rating",
    "entity": "review",
    "metric": "review attribute / listing",
    "grain": "review",
    "joins": [
      "productreview",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "rating",
      "minRating",
      "maxRating"
    ]
  },
  "worst_review": {
    "intent": "worst_review",
    "entity": "review",
    "metric": "review attribute / listing",
    "grain": "review",
    "joins": [
      "productreview",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": []
  },
  "best_review": {
    "intent": "best_review",
    "entity": "review",
    "metric": "review attribute / listing",
    "grain": "review",
    "joins": [
      "productreview",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": []
  },
  "latest_reviews": {
    "intent": "latest_reviews",
    "entity": "review",
    "metric": "row listing for latest_reviews",
    "grain": "review",
    "joins": [
      "productreview",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit"
    ]
  },
  "oldest_reviews": {
    "intent": "oldest_reviews",
    "entity": "review",
    "metric": "row listing for oldest_reviews",
    "grain": "review",
    "joins": [
      "productreview",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit"
    ]
  },
  "latest_review_date": {
    "intent": "latest_review_date",
    "entity": "review",
    "metric": "row listing for latest_review_date",
    "grain": "review",
    "joins": [
      "productreview",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit"
    ]
  },
  "list_reviews": {
    "intent": "list_reviews",
    "entity": "review",
    "metric": "row listing for list_reviews",
    "grain": "review",
    "joins": [
      "productreview",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit"
    ]
  },
  "list_reviewers": {
    "intent": "list_reviewers",
    "entity": "review",
    "metric": "row listing for list_reviewers",
    "grain": "review",
    "joins": [
      "productreview",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit",
      "reviewer",
      "reviewerContains"
    ]
  },
  "list_reviewed_products": {
    "intent": "list_reviewed_products",
    "entity": "review",
    "metric": "row listing for list_reviewed_products",
    "grain": "review",
    "joins": [
      "productreview",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit"
    ]
  },
  "review_by_id": {
    "intent": "review_by_id",
    "entity": "review",
    "metric": "review attribute / listing",
    "grain": "review",
    "joins": [
      "productreview",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "reviewId"
    ]
  },
  "sample_reviews": {
    "intent": "sample_reviews",
    "entity": "review",
    "metric": "row listing for sample_reviews",
    "grain": "review",
    "joins": [
      "productreview",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit"
    ]
  },
  "longest_review_comments": {
    "intent": "longest_review_comments",
    "entity": "review",
    "metric": "review attribute / listing",
    "grain": "review",
    "joins": [
      "productreview",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit",
      "hasComments"
    ]
  },
  "top_reviewer_by_count": {
    "intent": "top_reviewer_by_count",
    "entity": "review",
    "metric": "ranked list for top_reviewer_by_count",
    "grain": "review",
    "joins": [
      "productreview",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit",
      "reviewer",
      "reviewerContains"
    ]
  },
  "avg_rating_by_reviewer": {
    "intent": "avg_rating_by_reviewer",
    "entity": "review",
    "metric": "AVG(...) for avg_rating_by_reviewer",
    "grain": "group_row",
    "joins": [
      "productreview",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "rating",
      "minRating",
      "maxRating",
      "reviewer",
      "reviewerContains"
    ]
  },
  "avg_rating_by_year": {
    "intent": "avg_rating_by_year",
    "entity": "review",
    "metric": "AVG(...) for avg_rating_by_year",
    "grain": "group_row",
    "joins": [
      "productreview",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "timeField": "productreview.ReviewDate",
    "filtersAllowed": [
      "year",
      "years",
      "startYear",
      "endYear",
      "sellStartYear",
      "rating",
      "minRating",
      "maxRating"
    ]
  },
  "review_count_by_month": {
    "intent": "review_count_by_month",
    "entity": "review",
    "metric": "review attribute / listing",
    "grain": "review",
    "joins": [
      "productreview",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "timeField": "productreview.ReviewDate",
    "filtersAllowed": [
      "month"
    ]
  },
  "avg_rating_by_category": {
    "intent": "avg_rating_by_category",
    "entity": "review",
    "metric": "AVG(...) for avg_rating_by_category",
    "grain": "group_row",
    "joins": [
      "productreview",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "category",
      "rating",
      "minRating",
      "maxRating"
    ]
  },
  "avg_rating_by_subcategory": {
    "intent": "avg_rating_by_subcategory",
    "entity": "review",
    "metric": "AVG(...) for avg_rating_by_subcategory",
    "grain": "group_row",
    "joins": [
      "productreview",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "category",
      "subcategory",
      "rating",
      "minRating",
      "maxRating"
    ]
  },
  "avg_rating_by_color": {
    "intent": "avg_rating_by_color",
    "entity": "review",
    "metric": "AVG(...) for avg_rating_by_color",
    "grain": "group_row",
    "joins": [
      "productreview",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "color",
      "colors",
      "rating",
      "minRating",
      "maxRating"
    ]
  },
  "review_count_by_category": {
    "intent": "review_count_by_category",
    "entity": "review",
    "metric": "review attribute / listing",
    "grain": "review",
    "joins": [
      "productreview",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "category"
    ]
  },
  "review_count_by_model": {
    "intent": "review_count_by_model",
    "entity": "review",
    "metric": "review attribute / listing",
    "grain": "review",
    "joins": [
      "productreview",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "model"
    ]
  },
  "top_category_by_avg_rating": {
    "intent": "top_category_by_avg_rating",
    "entity": "review",
    "metric": "ranked list for top_category_by_avg_rating",
    "grain": "review",
    "joins": [
      "productreview",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit",
      "category",
      "rating",
      "minRating",
      "maxRating"
    ]
  },
  "compare_avg_rating_categories": {
    "intent": "compare_avg_rating_categories",
    "entity": "review",
    "metric": "review attribute / listing",
    "grain": "review",
    "joins": [
      "productreview",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "rating",
      "minRating",
      "maxRating",
      "categories"
    ]
  }
} as const;
