/**
 * intents.ts — salesorderheader catalog (order-level sales).
 * Does not own line-item rankings (see salesorderdetail).
 */
export const SALES_ORDER_HEADER_INTENTS = [
  "count_sales_orders",
  "last_sale",
  "first_sale",
  "sales_value_over_period",
  "average_order_value",
  "min_order_value",
  "max_order_value",
  "sales_orders_by_year",
  "count_online_orders",
  "count_offline_orders",
  "total_sales_value",
  "total_subtotal",
  "total_tax",
  "total_freight",
  "sales_value_by_year",
  "sales_value_by_month",
  "sales_orders_by_month",
  "sales_orders_by_status",
  "avg_order_value_by_year",
  "average_order_value_over_period",
  "count_orders_by_year",
  "sales_value_in_year",
  "count_orders_last_days",
  "list_orders_last_days",
  "count_orders_for_customer",
  "list_orders_for_customer",
  "order_by_id",
  "top_orders_by_value",
  "lowest_orders_by_value",
  "list_orders_min_value",
  "list_orders_max_value",
  "compare_sales_years",
  "sales_orders_by_territory",
  "avg_order_value_by_territory",
  "count_orders_with_po",
  "count_orders_without_comment",
  "list_orders_with_comments",
  "median_order_value",
  "average_freight",
  "average_tax",
  "count_orders_shipped_period",
  "latest_orders",
  "oldest_orders",
  "pct_online_orders",
  "variance_order_value",
  "list_orders_for_salesperson",
  "count_orders_for_salesperson",
  "last_sale_due_date",
  "last_sale_ship_date",
  "count_orders_by_status",
  "list_orders_by_status",
  "average_order_value_online",
  "average_order_value_offline",
  "sales_value_by_status",
  "sample_orders",
  "list_orders_year_range",
  "top_year_by_order_count",
  "top_year_by_sales_value",
  "count_distinct_customers_with_orders",
] as const;

export type SalesOrderHeaderIntent = (typeof SALES_ORDER_HEADER_INTENTS)[number];
