/**
 * semantics.ts — salesorderheader semantic layer (metric / grain / joins / filters).
 * Traceability for intents in this module. SQL templates remain in sql.ts;
 * the registry validates plans and FROM/JOIN tables against these defs.
 *
 * Generated by scripts/generate-table-semantics.cjs — edit carefully or re-generate.
 */
import type { SemanticDef } from "@/query-agent/domain/semantics/types";

export const SALES_ORDER_HEADER_SEMANTICS: Readonly<Record<string, SemanticDef>> = {
  "count_sales_orders": {
    "intent": "count_sales_orders",
    "entity": "salesorderheader",
    "metric": "COUNT(*) or distinct count for count_sales_orders",
    "grain": "scalar",
    "joins": [
      "salesorderheader"
    ],
    "filtersAllowed": []
  },
  "last_sale": {
    "intent": "last_sale",
    "entity": "salesorderheader",
    "metric": "order-level metric or listing",
    "grain": "order",
    "joins": [
      "salesorderheader"
    ],
    "timeField": "salesorderheader.OrderDate",
    "filtersAllowed": []
  },
  "first_sale": {
    "intent": "first_sale",
    "entity": "salesorderheader",
    "metric": "order-level metric or listing",
    "grain": "order",
    "joins": [
      "salesorderheader"
    ],
    "filtersAllowed": []
  },
  "sales_value_over_period": {
    "intent": "sales_value_over_period",
    "entity": "salesorderheader",
    "metric": "order-level metric or listing",
    "grain": "order",
    "joins": [
      "salesorderheader"
    ],
    "timeField": "salesorderheader.OrderDate",
    "filtersAllowed": [
      "lastMonths",
      "lastDays"
    ]
  },
  "average_order_value": {
    "intent": "average_order_value",
    "entity": "salesorderheader",
    "metric": "AVG(...) for average_order_value",
    "grain": "order",
    "joins": [
      "salesorderheader"
    ],
    "filtersAllowed": []
  },
  "min_order_value": {
    "intent": "min_order_value",
    "entity": "salesorderheader",
    "metric": "MIN(...) for min_order_value",
    "grain": "scalar",
    "joins": [
      "salesorderheader"
    ],
    "filtersAllowed": []
  },
  "max_order_value": {
    "intent": "max_order_value",
    "entity": "salesorderheader",
    "metric": "MAX(...) for max_order_value",
    "grain": "scalar",
    "joins": [
      "salesorderheader"
    ],
    "filtersAllowed": []
  },
  "sales_orders_by_year": {
    "intent": "sales_orders_by_year",
    "entity": "salesorderheader",
    "metric": "order-level metric or listing",
    "grain": "order",
    "joins": [
      "salesorderheader"
    ],
    "timeField": "salesorderheader.OrderDate",
    "filtersAllowed": [
      "year",
      "years",
      "startYear",
      "endYear",
      "sellStartYear"
    ]
  },
  "count_online_orders": {
    "intent": "count_online_orders",
    "entity": "salesorderheader",
    "metric": "COUNT(*) or distinct count for count_online_orders",
    "grain": "scalar",
    "joins": [
      "salesorderheader"
    ],
    "filtersAllowed": [
      "onlineOrderFlag"
    ]
  },
  "count_offline_orders": {
    "intent": "count_offline_orders",
    "entity": "salesorderheader",
    "metric": "COUNT(*) or distinct count for count_offline_orders",
    "grain": "scalar",
    "joins": [
      "salesorderheader"
    ],
    "filtersAllowed": []
  },
  "total_sales_value": {
    "intent": "total_sales_value",
    "entity": "salesorderheader",
    "metric": "SUM(...) for total_sales_value",
    "grain": "scalar",
    "joins": [
      "salesorderheader"
    ],
    "filtersAllowed": []
  },
  "total_subtotal": {
    "intent": "total_subtotal",
    "entity": "salesorderheader",
    "metric": "SUM(...) for total_subtotal",
    "grain": "scalar",
    "joins": [
      "salesorderheader"
    ],
    "filtersAllowed": []
  },
  "total_tax": {
    "intent": "total_tax",
    "entity": "salesorderheader",
    "metric": "SUM(...) for total_tax",
    "grain": "scalar",
    "joins": [
      "salesorderheader"
    ],
    "filtersAllowed": []
  },
  "total_freight": {
    "intent": "total_freight",
    "entity": "salesorderheader",
    "metric": "SUM(...) for total_freight",
    "grain": "scalar",
    "joins": [
      "salesorderheader"
    ],
    "filtersAllowed": []
  },
  "sales_value_by_year": {
    "intent": "sales_value_by_year",
    "entity": "salesorderheader",
    "metric": "order-level metric or listing",
    "grain": "order",
    "joins": [
      "salesorderheader"
    ],
    "timeField": "salesorderheader.OrderDate",
    "filtersAllowed": [
      "year",
      "years",
      "startYear",
      "endYear",
      "sellStartYear"
    ]
  },
  "sales_value_by_month": {
    "intent": "sales_value_by_month",
    "entity": "salesorderheader",
    "metric": "order-level metric or listing",
    "grain": "order",
    "joins": [
      "salesorderheader"
    ],
    "timeField": "salesorderheader.OrderDate",
    "filtersAllowed": [
      "month"
    ]
  },
  "sales_orders_by_month": {
    "intent": "sales_orders_by_month",
    "entity": "salesorderheader",
    "metric": "order-level metric or listing",
    "grain": "order",
    "joins": [
      "salesorderheader"
    ],
    "timeField": "salesorderheader.OrderDate",
    "filtersAllowed": [
      "month"
    ]
  },
  "sales_orders_by_status": {
    "intent": "sales_orders_by_status",
    "entity": "salesorderheader",
    "metric": "order-level metric or listing",
    "grain": "order",
    "joins": [
      "salesorderheader"
    ],
    "filtersAllowed": [
      "status"
    ]
  },
  "avg_order_value_by_year": {
    "intent": "avg_order_value_by_year",
    "entity": "salesorderheader",
    "metric": "AVG(...) for avg_order_value_by_year",
    "grain": "group_row",
    "joins": [
      "salesorderheader"
    ],
    "timeField": "salesorderheader.OrderDate",
    "filtersAllowed": [
      "year",
      "years",
      "startYear",
      "endYear",
      "sellStartYear"
    ]
  },
  "average_order_value_over_period": {
    "intent": "average_order_value_over_period",
    "entity": "salesorderheader",
    "metric": "AVG(...) for average_order_value_over_period",
    "grain": "order",
    "joins": [
      "salesorderheader"
    ],
    "timeField": "salesorderheader.OrderDate",
    "filtersAllowed": [
      "lastMonths",
      "lastDays"
    ]
  },
  "count_orders_by_year": {
    "intent": "count_orders_by_year",
    "entity": "salesorderheader",
    "metric": "COUNT(*) or distinct count for count_orders_by_year",
    "grain": "group_row",
    "joins": [
      "salesorderheader"
    ],
    "timeField": "salesorderheader.OrderDate",
    "filtersAllowed": [
      "year",
      "years",
      "startYear",
      "endYear",
      "sellStartYear"
    ]
  },
  "sales_value_in_year": {
    "intent": "sales_value_in_year",
    "entity": "salesorderheader",
    "metric": "order-level metric or listing",
    "grain": "order",
    "joins": [
      "salesorderheader"
    ],
    "timeField": "salesorderheader.OrderDate",
    "filtersAllowed": [
      "year",
      "years",
      "startYear",
      "endYear",
      "sellStartYear"
    ]
  },
  "count_orders_last_days": {
    "intent": "count_orders_last_days",
    "entity": "salesorderheader",
    "metric": "COUNT(*) or distinct count for count_orders_last_days",
    "grain": "scalar",
    "joins": [
      "salesorderheader"
    ],
    "timeField": "salesorderheader.OrderDate",
    "filtersAllowed": [
      "lastMonths",
      "lastDays"
    ]
  },
  "list_orders_last_days": {
    "intent": "list_orders_last_days",
    "entity": "salesorderheader",
    "metric": "row listing for list_orders_last_days",
    "grain": "order",
    "joins": [
      "salesorderheader"
    ],
    "timeField": "salesorderheader.OrderDate",
    "filtersAllowed": [
      "limit",
      "lastMonths",
      "lastDays"
    ]
  },
  "count_orders_for_customer": {
    "intent": "count_orders_for_customer",
    "entity": "salesorderheader",
    "metric": "COUNT(*) or distinct count for count_orders_for_customer",
    "grain": "scalar",
    "joins": [
      "salesorderheader"
    ],
    "filtersAllowed": [
      "customerId"
    ]
  },
  "list_orders_for_customer": {
    "intent": "list_orders_for_customer",
    "entity": "salesorderheader",
    "metric": "row listing for list_orders_for_customer",
    "grain": "order",
    "joins": [
      "salesorderheader"
    ],
    "filtersAllowed": [
      "limit",
      "customerId"
    ]
  },
  "order_by_id": {
    "intent": "order_by_id",
    "entity": "salesorderheader",
    "metric": "order-level metric or listing",
    "grain": "order",
    "joins": [
      "salesorderheader"
    ],
    "filtersAllowed": [
      "salesOrderId"
    ]
  },
  "top_orders_by_value": {
    "intent": "top_orders_by_value",
    "entity": "salesorderheader",
    "metric": "ranked list for top_orders_by_value",
    "grain": "order",
    "joins": [
      "salesorderheader"
    ],
    "filtersAllowed": [
      "limit"
    ]
  },
  "lowest_orders_by_value": {
    "intent": "lowest_orders_by_value",
    "entity": "salesorderheader",
    "metric": "ranked list for lowest_orders_by_value",
    "grain": "order",
    "joins": [
      "salesorderheader"
    ],
    "filtersAllowed": [
      "limit"
    ]
  },
  "list_orders_min_value": {
    "intent": "list_orders_min_value",
    "entity": "salesorderheader",
    "metric": "row listing for list_orders_min_value",
    "grain": "order",
    "joins": [
      "salesorderheader"
    ],
    "filtersAllowed": [
      "limit"
    ]
  },
  "list_orders_max_value": {
    "intent": "list_orders_max_value",
    "entity": "salesorderheader",
    "metric": "row listing for list_orders_max_value",
    "grain": "order",
    "joins": [
      "salesorderheader"
    ],
    "filtersAllowed": [
      "limit"
    ]
  },
  "compare_sales_years": {
    "intent": "compare_sales_years",
    "entity": "salesorderheader",
    "metric": "order-level metric or listing",
    "grain": "order",
    "joins": [
      "salesorderheader"
    ],
    "timeField": "salesorderheader.OrderDate",
    "filtersAllowed": [
      "year",
      "years",
      "startYear",
      "endYear",
      "sellStartYear"
    ]
  },
  "sales_orders_by_territory": {
    "intent": "sales_orders_by_territory",
    "entity": "salesorderheader",
    "metric": "order-level metric or listing",
    "grain": "order",
    "joins": [
      "salesorderheader"
    ],
    "filtersAllowed": [
      "territoryId"
    ]
  },
  "avg_order_value_by_territory": {
    "intent": "avg_order_value_by_territory",
    "entity": "salesorderheader",
    "metric": "AVG(...) for avg_order_value_by_territory",
    "grain": "group_row",
    "joins": [
      "salesorderheader"
    ],
    "filtersAllowed": [
      "territoryId"
    ]
  },
  "count_orders_with_po": {
    "intent": "count_orders_with_po",
    "entity": "salesorderheader",
    "metric": "COUNT(*) or distinct count for count_orders_with_po",
    "grain": "scalar",
    "joins": [
      "salesorderheader"
    ],
    "filtersAllowed": []
  },
  "count_orders_without_comment": {
    "intent": "count_orders_without_comment",
    "entity": "salesorderheader",
    "metric": "COUNT(*) or distinct count for count_orders_without_comment",
    "grain": "scalar",
    "joins": [
      "salesorderheader"
    ],
    "filtersAllowed": [
      "hasComments"
    ]
  },
  "list_orders_with_comments": {
    "intent": "list_orders_with_comments",
    "entity": "salesorderheader",
    "metric": "row listing for list_orders_with_comments",
    "grain": "order",
    "joins": [
      "salesorderheader"
    ],
    "filtersAllowed": [
      "limit",
      "hasComments"
    ]
  },
  "median_order_value": {
    "intent": "median_order_value",
    "entity": "salesorderheader",
    "metric": "median aggregate for median_order_value",
    "grain": "scalar",
    "joins": [
      "salesorderheader"
    ],
    "filtersAllowed": []
  },
  "average_freight": {
    "intent": "average_freight",
    "entity": "salesorderheader",
    "metric": "AVG(...) for average_freight",
    "grain": "order",
    "joins": [
      "salesorderheader"
    ],
    "filtersAllowed": []
  },
  "average_tax": {
    "intent": "average_tax",
    "entity": "salesorderheader",
    "metric": "AVG(...) for average_tax",
    "grain": "order",
    "joins": [
      "salesorderheader"
    ],
    "filtersAllowed": []
  },
  "count_orders_shipped_period": {
    "intent": "count_orders_shipped_period",
    "entity": "salesorderheader",
    "metric": "COUNT(*) or distinct count for count_orders_shipped_period",
    "grain": "scalar",
    "joins": [
      "salesorderheader"
    ],
    "timeField": "salesorderheader.ShipDate",
    "filtersAllowed": [
      "lastMonths",
      "lastDays"
    ]
  },
  "latest_orders": {
    "intent": "latest_orders",
    "entity": "salesorderheader",
    "metric": "row listing for latest_orders",
    "grain": "order",
    "joins": [
      "salesorderheader"
    ],
    "filtersAllowed": [
      "limit"
    ]
  },
  "oldest_orders": {
    "intent": "oldest_orders",
    "entity": "salesorderheader",
    "metric": "row listing for oldest_orders",
    "grain": "order",
    "joins": [
      "salesorderheader"
    ],
    "filtersAllowed": [
      "limit"
    ]
  },
  "pct_online_orders": {
    "intent": "pct_online_orders",
    "entity": "salesorderheader",
    "metric": "percentage for pct_online_orders",
    "grain": "scalar",
    "joins": [
      "salesorderheader"
    ],
    "filtersAllowed": [
      "onlineOrderFlag"
    ]
  },
  "variance_order_value": {
    "intent": "variance_order_value",
    "entity": "salesorderheader",
    "metric": "VARIANCE(...) for variance_order_value",
    "grain": "scalar",
    "joins": [
      "salesorderheader"
    ],
    "filtersAllowed": []
  },
  "list_orders_for_salesperson": {
    "intent": "list_orders_for_salesperson",
    "entity": "salesorderheader",
    "metric": "row listing for list_orders_for_salesperson",
    "grain": "order",
    "joins": [
      "salesorderheader"
    ],
    "filtersAllowed": [
      "limit",
      "salesPersonId"
    ]
  },
  "count_orders_for_salesperson": {
    "intent": "count_orders_for_salesperson",
    "entity": "salesorderheader",
    "metric": "COUNT(*) or distinct count for count_orders_for_salesperson",
    "grain": "scalar",
    "joins": [
      "salesorderheader"
    ],
    "filtersAllowed": [
      "salesPersonId"
    ]
  },
  "last_sale_due_date": {
    "intent": "last_sale_due_date",
    "entity": "salesorderheader",
    "metric": "order-level metric or listing",
    "grain": "order",
    "joins": [
      "salesorderheader"
    ],
    "timeField": "salesorderheader.DueDate",
    "filtersAllowed": []
  },
  "last_sale_ship_date": {
    "intent": "last_sale_ship_date",
    "entity": "salesorderheader",
    "metric": "order-level metric or listing",
    "grain": "order",
    "joins": [
      "salesorderheader"
    ],
    "timeField": "salesorderheader.ShipDate",
    "filtersAllowed": []
  },
  "count_orders_by_status": {
    "intent": "count_orders_by_status",
    "entity": "salesorderheader",
    "metric": "COUNT(*) or distinct count for count_orders_by_status",
    "grain": "group_row",
    "joins": [
      "salesorderheader"
    ],
    "filtersAllowed": [
      "status"
    ]
  },
  "list_orders_by_status": {
    "intent": "list_orders_by_status",
    "entity": "salesorderheader",
    "metric": "row listing for list_orders_by_status",
    "grain": "order",
    "joins": [
      "salesorderheader"
    ],
    "filtersAllowed": [
      "limit",
      "status"
    ]
  },
  "average_order_value_online": {
    "intent": "average_order_value_online",
    "entity": "salesorderheader",
    "metric": "AVG(...) for average_order_value_online",
    "grain": "order",
    "joins": [
      "salesorderheader"
    ],
    "filtersAllowed": [
      "onlineOrderFlag"
    ]
  },
  "average_order_value_offline": {
    "intent": "average_order_value_offline",
    "entity": "salesorderheader",
    "metric": "AVG(...) for average_order_value_offline",
    "grain": "order",
    "joins": [
      "salesorderheader"
    ],
    "filtersAllowed": []
  },
  "sales_value_by_status": {
    "intent": "sales_value_by_status",
    "entity": "salesorderheader",
    "metric": "order-level metric or listing",
    "grain": "order",
    "joins": [
      "salesorderheader"
    ],
    "filtersAllowed": [
      "status"
    ]
  },
  "sample_orders": {
    "intent": "sample_orders",
    "entity": "salesorderheader",
    "metric": "row listing for sample_orders",
    "grain": "order",
    "joins": [
      "salesorderheader"
    ],
    "filtersAllowed": [
      "limit"
    ]
  },
  "list_orders_year_range": {
    "intent": "list_orders_year_range",
    "entity": "salesorderheader",
    "metric": "row listing for list_orders_year_range",
    "grain": "order",
    "joins": [
      "salesorderheader"
    ],
    "timeField": "salesorderheader.OrderDate",
    "filtersAllowed": [
      "limit",
      "year",
      "years",
      "startYear",
      "endYear",
      "sellStartYear"
    ]
  },
  "top_year_by_order_count": {
    "intent": "top_year_by_order_count",
    "entity": "salesorderheader",
    "metric": "ranked list for top_year_by_order_count",
    "grain": "order",
    "joins": [
      "salesorderheader"
    ],
    "timeField": "salesorderheader.OrderDate",
    "filtersAllowed": [
      "limit",
      "year",
      "years",
      "startYear",
      "endYear",
      "sellStartYear"
    ]
  },
  "top_year_by_sales_value": {
    "intent": "top_year_by_sales_value",
    "entity": "salesorderheader",
    "metric": "ranked list for top_year_by_sales_value",
    "grain": "order",
    "joins": [
      "salesorderheader"
    ],
    "timeField": "salesorderheader.OrderDate",
    "filtersAllowed": [
      "limit",
      "year",
      "years",
      "startYear",
      "endYear",
      "sellStartYear"
    ]
  },
  "count_distinct_customers_with_orders": {
    "intent": "count_distinct_customers_with_orders",
    "entity": "salesorderheader",
    "metric": "COUNT(*) or distinct count for count_distinct_customers_with_orders",
    "grain": "scalar",
    "joins": [
      "salesorderheader"
    ],
    "filtersAllowed": []
  }
} as const;
