/**
 * intents.ts — salesorderdetail catalog (line items / product sales).
 * Does not own order-level totals (see salesorderheader).
 */
export const SALES_ORDER_DETAIL_INTENTS = [
  "count_order_lines",
  "top_products_by_sales",
  "least_sold_products",
  "sum_order_qty",
  "sales_qty_by_product",
  "top_products_by_revenue",
  "least_products_by_revenue",
  "avg_order_qty",
  "avg_unit_price",
  "sum_line_total",
  "line_total_by_product",
  "count_lines_for_order",
  "list_lines_for_order",
  "count_lines_for_product",
  "sales_qty_for_product",
  "list_lines_for_product",
  "avg_qty_by_product",
  "max_order_qty",
  "min_order_qty",
  "list_lines_min_qty",
  "list_lines_max_unit_price",
  "top_products_by_sales_category",
  "least_sold_products_category",
  "sales_qty_by_category",
  "line_total_by_category",
  "sales_qty_by_subcategory",
  "sales_qty_by_color",
  "top_products_by_sales_color",
  "count_distinct_products_sold",
  "count_products_never_sold",
  "list_sold_products",
  "avg_line_total",
  "median_order_qty",
  "variance_order_qty",
  "sales_qty_by_year",
  "line_total_by_year",
  "top_products_by_sales_period",
  "sum_order_qty_period",
  "compare_product_qty",
  "line_by_id",
  "sample_order_lines",
  "latest_order_lines",
  "sum_order_qty_category",
  "avg_unit_price_by_product",
  "count_discounted_lines",
  "list_discounted_lines",
  "sum_line_discount",
  "count_lines_online_orders",
  "sum_order_qty_finished_goods",
  "top_products_by_sales_max_price",
  "count_lines_with_tracking",
  "list_lines_without_tracking",
  "avg_lines_per_order",
  "orders_most_lines",
  "count_lines_by_special_offer",
  "pct_lines_for_product",
  "min_line_total",
  "max_line_total",
  "list_lines_for_color",
  "sum_order_qty_make_flag",
] as const;

export type SalesOrderDetailIntent = (typeof SALES_ORDER_DETAIL_INTENTS)[number];
