/**
 * semantics.ts — salesorderdetail semantic layer (metric / grain / joins / filters).
 * Traceability for intents in this module. SQL templates remain in sql.ts;
 * the registry validates plans and FROM/JOIN tables against these defs.
 *
 * Generated by scripts/generate-table-semantics.cjs — edit carefully or re-generate.
 */
import type { SemanticDef } from "@/query-agent/domain/semantics/types";

export const SALES_ORDER_DETAIL_SEMANTICS: Readonly<Record<string, SemanticDef>> = {
  "count_order_lines": {
    "intent": "count_order_lines",
    "entity": "salesorderdetail",
    "metric": "COUNT(*) or distinct count for count_order_lines",
    "grain": "scalar",
    "joins": [
      "salesorderdetail",
      "salesorderheader",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": []
  },
  "top_products_by_sales": {
    "intent": "top_products_by_sales",
    "entity": "salesorderdetail",
    "metric": "ranked list for top_products_by_sales",
    "grain": "order_line",
    "joins": [
      "salesorderdetail",
      "salesorderheader",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit"
    ]
  },
  "least_sold_products": {
    "intent": "least_sold_products",
    "entity": "salesorderdetail",
    "metric": "ranked list for least_sold_products",
    "grain": "order_line",
    "joins": [
      "salesorderdetail",
      "salesorderheader",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit"
    ]
  },
  "sum_order_qty": {
    "intent": "sum_order_qty",
    "entity": "salesorderdetail",
    "metric": "SUM(...) for sum_order_qty",
    "grain": "scalar",
    "joins": [
      "salesorderdetail",
      "salesorderheader",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": []
  },
  "sales_qty_by_product": {
    "intent": "sales_qty_by_product",
    "entity": "salesorderdetail",
    "metric": "line-item metric or listing",
    "grain": "order_line",
    "joins": [
      "salesorderdetail",
      "salesorderheader",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": []
  },
  "top_products_by_revenue": {
    "intent": "top_products_by_revenue",
    "entity": "salesorderdetail",
    "metric": "ranked list for top_products_by_revenue",
    "grain": "order_line",
    "joins": [
      "salesorderdetail",
      "salesorderheader",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit"
    ]
  },
  "least_products_by_revenue": {
    "intent": "least_products_by_revenue",
    "entity": "salesorderdetail",
    "metric": "ranked list for least_products_by_revenue",
    "grain": "order_line",
    "joins": [
      "salesorderdetail",
      "salesorderheader",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit"
    ]
  },
  "avg_order_qty": {
    "intent": "avg_order_qty",
    "entity": "salesorderdetail",
    "metric": "AVG(...) for avg_order_qty",
    "grain": "scalar",
    "joins": [
      "salesorderdetail",
      "salesorderheader",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": []
  },
  "avg_unit_price": {
    "intent": "avg_unit_price",
    "entity": "salesorderdetail",
    "metric": "AVG(...) for avg_unit_price",
    "grain": "scalar",
    "joins": [
      "salesorderdetail",
      "salesorderheader",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "maxPrice",
      "minPrice"
    ]
  },
  "sum_line_total": {
    "intent": "sum_line_total",
    "entity": "salesorderdetail",
    "metric": "SUM(...) for sum_line_total",
    "grain": "scalar",
    "joins": [
      "salesorderdetail",
      "salesorderheader",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": []
  },
  "line_total_by_product": {
    "intent": "line_total_by_product",
    "entity": "salesorderdetail",
    "metric": "line-item metric or listing",
    "grain": "order_line",
    "joins": [
      "salesorderdetail",
      "salesorderheader",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": []
  },
  "count_lines_for_order": {
    "intent": "count_lines_for_order",
    "entity": "salesorderdetail",
    "metric": "COUNT(*) or distinct count for count_lines_for_order",
    "grain": "scalar",
    "joins": [
      "salesorderdetail",
      "salesorderheader",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "salesOrderId"
    ]
  },
  "list_lines_for_order": {
    "intent": "list_lines_for_order",
    "entity": "salesorderdetail",
    "metric": "row listing for list_lines_for_order",
    "grain": "order_line",
    "joins": [
      "salesorderdetail",
      "salesorderheader",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit",
      "salesOrderId"
    ]
  },
  "count_lines_for_product": {
    "intent": "count_lines_for_product",
    "entity": "salesorderdetail",
    "metric": "COUNT(*) or distinct count for count_lines_for_product",
    "grain": "scalar",
    "joins": [
      "salesorderdetail",
      "salesorderheader",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "productId"
    ]
  },
  "sales_qty_for_product": {
    "intent": "sales_qty_for_product",
    "entity": "salesorderdetail",
    "metric": "line-item metric or listing",
    "grain": "order_line",
    "joins": [
      "salesorderdetail",
      "salesorderheader",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "productId"
    ]
  },
  "list_lines_for_product": {
    "intent": "list_lines_for_product",
    "entity": "salesorderdetail",
    "metric": "row listing for list_lines_for_product",
    "grain": "order_line",
    "joins": [
      "salesorderdetail",
      "salesorderheader",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit",
      "productId"
    ]
  },
  "avg_qty_by_product": {
    "intent": "avg_qty_by_product",
    "entity": "salesorderdetail",
    "metric": "AVG(...) for avg_qty_by_product",
    "grain": "group_row",
    "joins": [
      "salesorderdetail",
      "salesorderheader",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": []
  },
  "max_order_qty": {
    "intent": "max_order_qty",
    "entity": "salesorderdetail",
    "metric": "MAX(...) for max_order_qty",
    "grain": "scalar",
    "joins": [
      "salesorderdetail",
      "salesorderheader",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": []
  },
  "min_order_qty": {
    "intent": "min_order_qty",
    "entity": "salesorderdetail",
    "metric": "MIN(...) for min_order_qty",
    "grain": "scalar",
    "joins": [
      "salesorderdetail",
      "salesorderheader",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": []
  },
  "list_lines_min_qty": {
    "intent": "list_lines_min_qty",
    "entity": "salesorderdetail",
    "metric": "row listing for list_lines_min_qty",
    "grain": "order_line",
    "joins": [
      "salesorderdetail",
      "salesorderheader",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit"
    ]
  },
  "list_lines_max_unit_price": {
    "intent": "list_lines_max_unit_price",
    "entity": "salesorderdetail",
    "metric": "row listing for list_lines_max_unit_price",
    "grain": "order_line",
    "joins": [
      "salesorderdetail",
      "salesorderheader",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit",
      "maxPrice",
      "minPrice"
    ]
  },
  "top_products_by_sales_category": {
    "intent": "top_products_by_sales_category",
    "entity": "salesorderdetail",
    "metric": "ranked list for top_products_by_sales_category",
    "grain": "order_line",
    "joins": [
      "salesorderdetail",
      "salesorderheader",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit",
      "category"
    ]
  },
  "least_sold_products_category": {
    "intent": "least_sold_products_category",
    "entity": "salesorderdetail",
    "metric": "ranked list for least_sold_products_category",
    "grain": "order_line",
    "joins": [
      "salesorderdetail",
      "salesorderheader",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit",
      "category"
    ]
  },
  "sales_qty_by_category": {
    "intent": "sales_qty_by_category",
    "entity": "salesorderdetail",
    "metric": "line-item metric or listing",
    "grain": "order_line",
    "joins": [
      "salesorderdetail",
      "salesorderheader",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "category"
    ]
  },
  "line_total_by_category": {
    "intent": "line_total_by_category",
    "entity": "salesorderdetail",
    "metric": "line-item metric or listing",
    "grain": "order_line",
    "joins": [
      "salesorderdetail",
      "salesorderheader",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "category"
    ]
  },
  "sales_qty_by_subcategory": {
    "intent": "sales_qty_by_subcategory",
    "entity": "salesorderdetail",
    "metric": "line-item metric or listing",
    "grain": "order_line",
    "joins": [
      "salesorderdetail",
      "salesorderheader",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "category",
      "subcategory"
    ]
  },
  "sales_qty_by_color": {
    "intent": "sales_qty_by_color",
    "entity": "salesorderdetail",
    "metric": "line-item metric or listing",
    "grain": "order_line",
    "joins": [
      "salesorderdetail",
      "salesorderheader",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "color",
      "colors"
    ]
  },
  "top_products_by_sales_color": {
    "intent": "top_products_by_sales_color",
    "entity": "salesorderdetail",
    "metric": "ranked list for top_products_by_sales_color",
    "grain": "order_line",
    "joins": [
      "salesorderdetail",
      "salesorderheader",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit",
      "color",
      "colors"
    ]
  },
  "count_distinct_products_sold": {
    "intent": "count_distinct_products_sold",
    "entity": "salesorderdetail",
    "metric": "COUNT(*) or distinct count for count_distinct_products_sold",
    "grain": "scalar",
    "joins": [
      "salesorderdetail",
      "salesorderheader",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": []
  },
  "count_products_never_sold": {
    "intent": "count_products_never_sold",
    "entity": "salesorderdetail",
    "metric": "COUNT(*) or distinct count for count_products_never_sold",
    "grain": "scalar",
    "joins": [
      "salesorderdetail",
      "salesorderheader",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": []
  },
  "list_sold_products": {
    "intent": "list_sold_products",
    "entity": "salesorderdetail",
    "metric": "row listing for list_sold_products",
    "grain": "order_line",
    "joins": [
      "salesorderdetail",
      "salesorderheader",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit"
    ]
  },
  "avg_line_total": {
    "intent": "avg_line_total",
    "entity": "salesorderdetail",
    "metric": "AVG(...) for avg_line_total",
    "grain": "scalar",
    "joins": [
      "salesorderdetail",
      "salesorderheader",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": []
  },
  "median_order_qty": {
    "intent": "median_order_qty",
    "entity": "salesorderdetail",
    "metric": "median aggregate for median_order_qty",
    "grain": "scalar",
    "joins": [
      "salesorderdetail",
      "salesorderheader",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": []
  },
  "variance_order_qty": {
    "intent": "variance_order_qty",
    "entity": "salesorderdetail",
    "metric": "VARIANCE(...) for variance_order_qty",
    "grain": "scalar",
    "joins": [
      "salesorderdetail",
      "salesorderheader",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": []
  },
  "sales_qty_by_year": {
    "intent": "sales_qty_by_year",
    "entity": "salesorderdetail",
    "metric": "line-item metric or listing",
    "grain": "order_line",
    "joins": [
      "salesorderdetail",
      "salesorderheader",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "timeField": "salesorderheader.OrderDate",
    "filtersAllowed": [
      "year",
      "years",
      "startYear",
      "endYear",
      "sellStartYear"
    ]
  },
  "line_total_by_year": {
    "intent": "line_total_by_year",
    "entity": "salesorderdetail",
    "metric": "line-item metric or listing",
    "grain": "order_line",
    "joins": [
      "salesorderdetail",
      "salesorderheader",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "timeField": "salesorderheader.OrderDate",
    "filtersAllowed": [
      "year",
      "years",
      "startYear",
      "endYear",
      "sellStartYear"
    ]
  },
  "top_products_by_sales_period": {
    "intent": "top_products_by_sales_period",
    "entity": "salesorderdetail",
    "metric": "ranked list for top_products_by_sales_period",
    "grain": "order_line",
    "joins": [
      "salesorderdetail",
      "salesorderheader",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "timeField": "salesorderheader.OrderDate",
    "filtersAllowed": [
      "limit",
      "lastMonths",
      "lastDays"
    ]
  },
  "sum_order_qty_period": {
    "intent": "sum_order_qty_period",
    "entity": "salesorderdetail",
    "metric": "SUM(...) for sum_order_qty_period",
    "grain": "scalar",
    "joins": [
      "salesorderdetail",
      "salesorderheader",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "timeField": "salesorderheader.OrderDate",
    "filtersAllowed": [
      "lastMonths",
      "lastDays"
    ]
  },
  "compare_product_qty": {
    "intent": "compare_product_qty",
    "entity": "salesorderdetail",
    "metric": "line-item metric or listing",
    "grain": "order_line",
    "joins": [
      "salesorderdetail",
      "salesorderheader",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "productIds"
    ]
  },
  "line_by_id": {
    "intent": "line_by_id",
    "entity": "salesorderdetail",
    "metric": "line-item metric or listing",
    "grain": "order_line",
    "joins": [
      "salesorderdetail",
      "salesorderheader",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "salesOrderDetailId"
    ]
  },
  "sample_order_lines": {
    "intent": "sample_order_lines",
    "entity": "salesorderdetail",
    "metric": "row listing for sample_order_lines",
    "grain": "order_line",
    "joins": [
      "salesorderdetail",
      "salesorderheader",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit"
    ]
  },
  "latest_order_lines": {
    "intent": "latest_order_lines",
    "entity": "salesorderdetail",
    "metric": "row listing for latest_order_lines",
    "grain": "order_line",
    "joins": [
      "salesorderdetail",
      "salesorderheader",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit"
    ]
  },
  "sum_order_qty_category": {
    "intent": "sum_order_qty_category",
    "entity": "salesorderdetail",
    "metric": "SUM(...) for sum_order_qty_category",
    "grain": "scalar",
    "joins": [
      "salesorderdetail",
      "salesorderheader",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "category"
    ]
  },
  "avg_unit_price_by_product": {
    "intent": "avg_unit_price_by_product",
    "entity": "salesorderdetail",
    "metric": "AVG(...) for avg_unit_price_by_product",
    "grain": "group_row",
    "joins": [
      "salesorderdetail",
      "salesorderheader",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "maxPrice",
      "minPrice"
    ]
  },
  "count_discounted_lines": {
    "intent": "count_discounted_lines",
    "entity": "salesorderdetail",
    "metric": "COUNT(*) or distinct count for count_discounted_lines",
    "grain": "scalar",
    "joins": [
      "salesorderdetail",
      "salesorderheader",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": []
  },
  "list_discounted_lines": {
    "intent": "list_discounted_lines",
    "entity": "salesorderdetail",
    "metric": "row listing for list_discounted_lines",
    "grain": "order_line",
    "joins": [
      "salesorderdetail",
      "salesorderheader",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit"
    ]
  },
  "sum_line_discount": {
    "intent": "sum_line_discount",
    "entity": "salesorderdetail",
    "metric": "SUM(...) for sum_line_discount",
    "grain": "scalar",
    "joins": [
      "salesorderdetail",
      "salesorderheader",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": []
  },
  "count_lines_online_orders": {
    "intent": "count_lines_online_orders",
    "entity": "salesorderdetail",
    "metric": "COUNT(*) or distinct count for count_lines_online_orders",
    "grain": "scalar",
    "joins": [
      "salesorderdetail",
      "salesorderheader",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "onlineOrderFlag"
    ]
  },
  "sum_order_qty_finished_goods": {
    "intent": "sum_order_qty_finished_goods",
    "entity": "salesorderdetail",
    "metric": "SUM(...) for sum_order_qty_finished_goods",
    "grain": "scalar",
    "joins": [
      "salesorderdetail",
      "salesorderheader",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "finishedGoodsFlag"
    ]
  },
  "top_products_by_sales_max_price": {
    "intent": "top_products_by_sales_max_price",
    "entity": "salesorderdetail",
    "metric": "ranked list for top_products_by_sales_max_price",
    "grain": "order_line",
    "joins": [
      "salesorderdetail",
      "salesorderheader",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit",
      "maxPrice",
      "minPrice"
    ]
  },
  "count_lines_with_tracking": {
    "intent": "count_lines_with_tracking",
    "entity": "salesorderdetail",
    "metric": "COUNT(*) or distinct count for count_lines_with_tracking",
    "grain": "scalar",
    "joins": [
      "salesorderdetail",
      "salesorderheader",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": []
  },
  "list_lines_without_tracking": {
    "intent": "list_lines_without_tracking",
    "entity": "salesorderdetail",
    "metric": "row listing for list_lines_without_tracking",
    "grain": "order_line",
    "joins": [
      "salesorderdetail",
      "salesorderheader",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit"
    ]
  },
  "avg_lines_per_order": {
    "intent": "avg_lines_per_order",
    "entity": "salesorderdetail",
    "metric": "AVG(...) for avg_lines_per_order",
    "grain": "group_row",
    "joins": [
      "salesorderdetail",
      "salesorderheader",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": []
  },
  "orders_most_lines": {
    "intent": "orders_most_lines",
    "entity": "salesorderdetail",
    "metric": "line-item metric or listing",
    "grain": "order_line",
    "joins": [
      "salesorderdetail",
      "salesorderheader",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": []
  },
  "count_lines_by_special_offer": {
    "intent": "count_lines_by_special_offer",
    "entity": "salesorderdetail",
    "metric": "COUNT(*) or distinct count for count_lines_by_special_offer",
    "grain": "group_row",
    "joins": [
      "salesorderdetail",
      "salesorderheader",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "specialOfferId"
    ]
  },
  "pct_lines_for_product": {
    "intent": "pct_lines_for_product",
    "entity": "salesorderdetail",
    "metric": "percentage for pct_lines_for_product",
    "grain": "scalar",
    "joins": [
      "salesorderdetail",
      "salesorderheader",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "productId"
    ]
  },
  "min_line_total": {
    "intent": "min_line_total",
    "entity": "salesorderdetail",
    "metric": "MIN(...) for min_line_total",
    "grain": "scalar",
    "joins": [
      "salesorderdetail",
      "salesorderheader",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": []
  },
  "max_line_total": {
    "intent": "max_line_total",
    "entity": "salesorderdetail",
    "metric": "MAX(...) for max_line_total",
    "grain": "scalar",
    "joins": [
      "salesorderdetail",
      "salesorderheader",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": []
  },
  "list_lines_for_color": {
    "intent": "list_lines_for_color",
    "entity": "salesorderdetail",
    "metric": "row listing for list_lines_for_color",
    "grain": "order_line",
    "joins": [
      "salesorderdetail",
      "salesorderheader",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit",
      "color",
      "colors"
    ]
  },
  "sum_order_qty_make_flag": {
    "intent": "sum_order_qty_make_flag",
    "entity": "salesorderdetail",
    "metric": "SUM(...) for sum_order_qty_make_flag",
    "grain": "scalar",
    "joins": [
      "salesorderdetail",
      "salesorderheader",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "makeFlag"
    ]
  }
} as const;
