/**
 * intents.ts — Product entity intent catalog.
 * Declares the canonical intent names for product-related questions
 * (client tables: product, productsubcategory, productcategory).
 * No SQL, heuristics, or answer formatting live here.
 */
export const PRODUCT_INTENTS = [
  "count_products",
  "count_products_without_subcategory",
  "count_products_without_color",
  "count_products_with_color",
  "count_products_under_price",
  "count_products_over_price",
  "count_products_zero_price",
  "count_products_make_flag",
  "count_finished_goods",
  "count_sellable_products",
  "count_products_zero_safety_stock",
  "count_products_without_model",
  "count_distinct_colors",
  "count_categories",
  "count_subcategories",
  "list_categories",
  "list_subcategories",
  "list_product_lines",
  "list_discontinued_products",
  "top_category_by_product_count",
  "bottom_subcategory_by_product_count",
  "top_color_by_product_count",
  "avg_list_price",
  "median_list_price",
  "cheapest_product",
  "most_expensive_product",
  "top_cheapest_products",
  "top_heavy_products",
  "products_price_above_cost",
  "avg_margin_by_category",
  "products_by_category",
  "products_by_subcategory",
  "products_by_size",
  "products_by_class",
  "products_by_style",
  "products_by_model",
  "avg_list_price_by_category",
  "avg_list_price_by_subcategory",
  "avg_list_price_by_color",
  "avg_weight_by_category",
  "avg_days_to_manufacture_by_category",
  "min_list_price_by_category",
  "max_list_price_by_category",
  "sum_list_price_by_category",
  "products_by_color",
  "list_products",
  "list_products_by_weight",
  "product_by_id",
  "product_list_price_by_id",
  "newest_products_by_sell_start",
  "subcategories_by_category",
  "category_for_subcategory",
  "compare_avg_price_categories",
  "sample_products",
  "top_expensive_products",
  "cheapest_products_under_price",
] as const;

export type ProductIntent = (typeof PRODUCT_INTENTS)[number];
