/**
 * semantics.ts — product semantic layer (metric / grain / joins / filters).
 * Traceability for intents in this module. SQL templates remain in sql.ts;
 * the registry validates plans and FROM/JOIN tables against these defs.
 *
 * Generated by scripts/generate-table-semantics.cjs — edit carefully or re-generate.
 */
import type { SemanticDef } from "@/query-agent/domain/semantics/types";

export const PRODUCT_SEMANTICS: Readonly<Record<string, SemanticDef>> = {
  "count_products": {
    "intent": "count_products",
    "entity": "product",
    "metric": "COUNT(*) or distinct count for count_products",
    "grain": "scalar",
    "joins": [
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": []
  },
  "count_products_without_subcategory": {
    "intent": "count_products_without_subcategory",
    "entity": "product",
    "metric": "COUNT(*) or distinct count for count_products_without_subcategory",
    "grain": "scalar",
    "joins": [
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "category",
      "subcategory"
    ]
  },
  "count_products_without_color": {
    "intent": "count_products_without_color",
    "entity": "product",
    "metric": "COUNT(*) or distinct count for count_products_without_color",
    "grain": "scalar",
    "joins": [
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "color",
      "colors"
    ]
  },
  "count_products_with_color": {
    "intent": "count_products_with_color",
    "entity": "product",
    "metric": "COUNT(*) or distinct count for count_products_with_color",
    "grain": "scalar",
    "joins": [
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "color",
      "colors"
    ]
  },
  "count_products_under_price": {
    "intent": "count_products_under_price",
    "entity": "product",
    "metric": "COUNT(*) or distinct count for count_products_under_price",
    "grain": "scalar",
    "joins": [
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "maxPrice",
      "minPrice"
    ]
  },
  "count_products_over_price": {
    "intent": "count_products_over_price",
    "entity": "product",
    "metric": "COUNT(*) or distinct count for count_products_over_price",
    "grain": "scalar",
    "joins": [
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "maxPrice",
      "minPrice"
    ]
  },
  "count_products_zero_price": {
    "intent": "count_products_zero_price",
    "entity": "product",
    "metric": "COUNT(*) or distinct count for count_products_zero_price",
    "grain": "scalar",
    "joins": [
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "maxPrice",
      "minPrice"
    ]
  },
  "count_products_make_flag": {
    "intent": "count_products_make_flag",
    "entity": "product",
    "metric": "COUNT(*) or distinct count for count_products_make_flag",
    "grain": "scalar",
    "joins": [
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "makeFlag"
    ]
  },
  "count_finished_goods": {
    "intent": "count_finished_goods",
    "entity": "product",
    "metric": "COUNT(*) or distinct count for count_finished_goods",
    "grain": "scalar",
    "joins": [
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "finishedGoodsFlag"
    ]
  },
  "count_sellable_products": {
    "intent": "count_sellable_products",
    "entity": "product",
    "metric": "COUNT(*) or distinct count for count_sellable_products",
    "grain": "scalar",
    "joins": [
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": []
  },
  "count_products_zero_safety_stock": {
    "intent": "count_products_zero_safety_stock",
    "entity": "product",
    "metric": "COUNT(*) or distinct count for count_products_zero_safety_stock",
    "grain": "scalar",
    "joins": [
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": []
  },
  "count_products_without_model": {
    "intent": "count_products_without_model",
    "entity": "product",
    "metric": "COUNT(*) or distinct count for count_products_without_model",
    "grain": "scalar",
    "joins": [
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "model"
    ]
  },
  "count_distinct_colors": {
    "intent": "count_distinct_colors",
    "entity": "product",
    "metric": "COUNT(*) or distinct count for count_distinct_colors",
    "grain": "scalar",
    "joins": [
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "color",
      "colors"
    ]
  },
  "count_categories": {
    "intent": "count_categories",
    "entity": "product",
    "metric": "COUNT(*) or distinct count for count_categories",
    "grain": "scalar",
    "joins": [
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": []
  },
  "count_subcategories": {
    "intent": "count_subcategories",
    "entity": "product",
    "metric": "COUNT(*) or distinct count for count_subcategories",
    "grain": "scalar",
    "joins": [
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "subcategory"
    ]
  },
  "list_categories": {
    "intent": "list_categories",
    "entity": "product",
    "metric": "row listing for list_categories",
    "grain": "product",
    "joins": [
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit"
    ]
  },
  "list_subcategories": {
    "intent": "list_subcategories",
    "entity": "product",
    "metric": "row listing for list_subcategories",
    "grain": "product",
    "joins": [
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit",
      "subcategory"
    ]
  },
  "list_product_lines": {
    "intent": "list_product_lines",
    "entity": "product",
    "metric": "row listing for list_product_lines",
    "grain": "product",
    "joins": [
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit",
      "productLine"
    ]
  },
  "list_discontinued_products": {
    "intent": "list_discontinued_products",
    "entity": "product",
    "metric": "row listing for list_discontinued_products",
    "grain": "product",
    "joins": [
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit"
    ]
  },
  "top_category_by_product_count": {
    "intent": "top_category_by_product_count",
    "entity": "product",
    "metric": "ranked list for top_category_by_product_count",
    "grain": "product",
    "joins": [
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit",
      "category"
    ]
  },
  "bottom_subcategory_by_product_count": {
    "intent": "bottom_subcategory_by_product_count",
    "entity": "product",
    "metric": "product attribute / listing",
    "grain": "product",
    "joins": [
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "category",
      "subcategory"
    ]
  },
  "top_color_by_product_count": {
    "intent": "top_color_by_product_count",
    "entity": "product",
    "metric": "ranked list for top_color_by_product_count",
    "grain": "product",
    "joins": [
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit",
      "color",
      "colors"
    ]
  },
  "avg_list_price": {
    "intent": "avg_list_price",
    "entity": "product",
    "metric": "AVG(...) for avg_list_price",
    "grain": "scalar",
    "joins": [
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit",
      "maxPrice",
      "minPrice"
    ]
  },
  "median_list_price": {
    "intent": "median_list_price",
    "entity": "product",
    "metric": "median aggregate for median_list_price",
    "grain": "scalar",
    "joins": [
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit",
      "maxPrice",
      "minPrice"
    ]
  },
  "cheapest_product": {
    "intent": "cheapest_product",
    "entity": "product",
    "metric": "product attribute / listing",
    "grain": "product",
    "joins": [
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "maxPrice",
      "minPrice"
    ]
  },
  "most_expensive_product": {
    "intent": "most_expensive_product",
    "entity": "product",
    "metric": "product attribute / listing",
    "grain": "product",
    "joins": [
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "maxPrice",
      "minPrice"
    ]
  },
  "top_cheapest_products": {
    "intent": "top_cheapest_products",
    "entity": "product",
    "metric": "ranked list for top_cheapest_products",
    "grain": "product",
    "joins": [
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit",
      "maxPrice",
      "minPrice"
    ]
  },
  "top_heavy_products": {
    "intent": "top_heavy_products",
    "entity": "product",
    "metric": "ranked list for top_heavy_products",
    "grain": "product",
    "joins": [
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit"
    ]
  },
  "products_price_above_cost": {
    "intent": "products_price_above_cost",
    "entity": "product",
    "metric": "product attribute / listing",
    "grain": "product",
    "joins": [
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "maxPrice",
      "minPrice"
    ]
  },
  "avg_margin_by_category": {
    "intent": "avg_margin_by_category",
    "entity": "product",
    "metric": "AVG(...) for avg_margin_by_category",
    "grain": "group_row",
    "joins": [
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "category"
    ]
  },
  "products_by_category": {
    "intent": "products_by_category",
    "entity": "product",
    "metric": "product attribute / listing",
    "grain": "product",
    "joins": [
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "category"
    ]
  },
  "products_by_subcategory": {
    "intent": "products_by_subcategory",
    "entity": "product",
    "metric": "product attribute / listing",
    "grain": "product",
    "joins": [
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "category",
      "subcategory"
    ]
  },
  "products_by_size": {
    "intent": "products_by_size",
    "entity": "product",
    "metric": "product attribute / listing",
    "grain": "product",
    "joins": [
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "size"
    ]
  },
  "products_by_class": {
    "intent": "products_by_class",
    "entity": "product",
    "metric": "product attribute / listing",
    "grain": "product",
    "joins": [
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "class"
    ]
  },
  "products_by_style": {
    "intent": "products_by_style",
    "entity": "product",
    "metric": "product attribute / listing",
    "grain": "product",
    "joins": [
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "style"
    ]
  },
  "products_by_model": {
    "intent": "products_by_model",
    "entity": "product",
    "metric": "product attribute / listing",
    "grain": "product",
    "joins": [
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "model"
    ]
  },
  "avg_list_price_by_category": {
    "intent": "avg_list_price_by_category",
    "entity": "product",
    "metric": "AVG(...) for avg_list_price_by_category",
    "grain": "group_row",
    "joins": [
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit",
      "category",
      "maxPrice",
      "minPrice"
    ]
  },
  "avg_list_price_by_subcategory": {
    "intent": "avg_list_price_by_subcategory",
    "entity": "product",
    "metric": "AVG(...) for avg_list_price_by_subcategory",
    "grain": "group_row",
    "joins": [
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit",
      "category",
      "subcategory",
      "maxPrice",
      "minPrice"
    ]
  },
  "avg_list_price_by_color": {
    "intent": "avg_list_price_by_color",
    "entity": "product",
    "metric": "AVG(...) for avg_list_price_by_color",
    "grain": "group_row",
    "joins": [
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit",
      "color",
      "colors",
      "maxPrice",
      "minPrice"
    ]
  },
  "avg_weight_by_category": {
    "intent": "avg_weight_by_category",
    "entity": "product",
    "metric": "AVG(...) for avg_weight_by_category",
    "grain": "group_row",
    "joins": [
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "category",
      "minWeight"
    ]
  },
  "avg_days_to_manufacture_by_category": {
    "intent": "avg_days_to_manufacture_by_category",
    "entity": "product",
    "metric": "AVG(...) for avg_days_to_manufacture_by_category",
    "grain": "group_row",
    "joins": [
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "timeField": "product.SellStartDate",
    "filtersAllowed": [
      "category",
      "minDaysToManufacture"
    ]
  },
  "min_list_price_by_category": {
    "intent": "min_list_price_by_category",
    "entity": "product",
    "metric": "MIN(...) for min_list_price_by_category",
    "grain": "group_row",
    "joins": [
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit",
      "category",
      "maxPrice",
      "minPrice"
    ]
  },
  "max_list_price_by_category": {
    "intent": "max_list_price_by_category",
    "entity": "product",
    "metric": "MAX(...) for max_list_price_by_category",
    "grain": "group_row",
    "joins": [
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit",
      "category",
      "maxPrice",
      "minPrice"
    ]
  },
  "sum_list_price_by_category": {
    "intent": "sum_list_price_by_category",
    "entity": "product",
    "metric": "SUM(...) for sum_list_price_by_category",
    "grain": "group_row",
    "joins": [
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit",
      "category",
      "maxPrice",
      "minPrice"
    ]
  },
  "products_by_color": {
    "intent": "products_by_color",
    "entity": "product",
    "metric": "product attribute / listing",
    "grain": "product",
    "joins": [
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "color",
      "colors"
    ]
  },
  "list_products": {
    "intent": "list_products",
    "entity": "product",
    "metric": "row listing for list_products",
    "grain": "product",
    "joins": [
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit",
      "maxPrice",
      "minPrice",
      "color",
      "colors",
      "size",
      "category",
      "subcategory",
      "nameContains",
      "productNumberPrefix",
      "productLine",
      "finishedGoodsFlag",
      "sellStartYear",
      "minDaysToManufacture",
      "minReorderPoint",
      "includeZeroPrice"
    ]
  },
  "list_products_by_weight": {
    "intent": "list_products_by_weight",
    "entity": "product",
    "metric": "row listing for list_products_by_weight",
    "grain": "product",
    "joins": [
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit",
      "minWeight",
      "maxPrice",
      "minPrice",
      "color",
      "colors",
      "size",
      "category",
      "subcategory",
      "nameContains",
      "productNumberPrefix",
      "productLine",
      "finishedGoodsFlag",
      "sellStartYear",
      "minDaysToManufacture",
      "minReorderPoint",
      "includeZeroPrice"
    ]
  },
  "product_by_id": {
    "intent": "product_by_id",
    "entity": "product",
    "metric": "product attribute / listing",
    "grain": "product",
    "joins": [
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "productId"
    ]
  },
  "product_list_price_by_id": {
    "intent": "product_list_price_by_id",
    "entity": "product",
    "metric": "product attribute / listing",
    "grain": "product",
    "joins": [
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit",
      "maxPrice",
      "minPrice"
    ]
  },
  "newest_products_by_sell_start": {
    "intent": "newest_products_by_sell_start",
    "entity": "product",
    "metric": "product attribute / listing",
    "grain": "product",
    "joins": [
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "timeField": "product.SellStartDate",
    "filtersAllowed": [
      "year",
      "years",
      "startYear",
      "endYear",
      "sellStartYear"
    ]
  },
  "subcategories_by_category": {
    "intent": "subcategories_by_category",
    "entity": "product",
    "metric": "product attribute / listing",
    "grain": "product",
    "joins": [
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "category",
      "subcategory"
    ]
  },
  "category_for_subcategory": {
    "intent": "category_for_subcategory",
    "entity": "product",
    "metric": "product attribute / listing",
    "grain": "product",
    "joins": [
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "category",
      "subcategory"
    ]
  },
  "compare_avg_price_categories": {
    "intent": "compare_avg_price_categories",
    "entity": "product",
    "metric": "product attribute / listing",
    "grain": "product",
    "joins": [
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "maxPrice",
      "minPrice",
      "categories"
    ]
  },
  "sample_products": {
    "intent": "sample_products",
    "entity": "product",
    "metric": "row listing for sample_products",
    "grain": "product",
    "joins": [
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit"
    ]
  },
  "top_expensive_products": {
    "intent": "top_expensive_products",
    "entity": "product",
    "metric": "ranked list for top_expensive_products",
    "grain": "product",
    "joins": [
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit",
      "maxPrice",
      "minPrice"
    ]
  },
  "cheapest_products_under_price": {
    "intent": "cheapest_products_under_price",
    "entity": "product",
    "metric": "product attribute / listing",
    "grain": "product",
    "joins": [
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "maxPrice",
      "minPrice"
    ]
  }
} as const;
