/**
 * intents.ts — customer catalog (CustomerID / AccountNumber / CustomerType).
 * Person/contact via LEFT JOIN individual → contact (name, email, phone, …).
 * Spend rankings join salesorderheader (+ detail/product for category).
 * Never expose PasswordHash / PasswordSalt.
 */
export const CUSTOMER_INTENTS = [
  "count_customers",
  "count_customers_by_type",
  "customers_by_type",
  "count_customers_by_territory",
  "customers_by_territory",
  "customer_by_id",
  "customer_by_account",
  "list_customers",
  "sample_customers",
  "latest_customers",
  "oldest_customers",
  "count_customers_with_orders",
  "count_customers_without_orders",
  "pct_customers_with_orders",
  "list_customers_with_orders",
  "list_customers_without_orders",
  "top_customers_by_sales",
  "lowest_customers_by_sales",
  "top_customers_by_order_count",
  "lowest_customers_by_order_count",
  "customers_by_category_spend",
  "avg_customer_spend",
  "median_customer_spend",
  "sum_customer_spend",
  "max_customer_spend",
  "min_customer_spend",
  "avg_orders_per_customer",
  "customer_spend_for_id",
  "customer_order_count_for_id",
  "customers_spend_over",
  "customers_spend_under",
  "customers_with_min_orders",
  "top_customers_by_sales_period",
  "top_customers_by_sales_type",
  "top_customers_by_sales_territory",
  "avg_spend_by_type",
  "avg_spend_by_territory",
  "customer_count_by_territory_type",
  "compare_customer_types_spend",
  "pct_customers_by_type",
  "variance_customer_spend",
  "customers_modified_after",
  "count_store_customers",
  "count_individual_customers",
  "random_sample_store_customers",
  "top_account_numbers_by_sales",
  "customers_by_name",
  "count_customers_by_name",
  "orders_for_customers_by_name",
] as const;

export type CustomerIntent = (typeof CUSTOMER_INTENTS)[number];
