/**
 * semantics.ts — customer semantic layer (metric / grain / joins / filters).
 * Traceability for intents in this module. SQL templates remain in sql.ts;
 * the registry validates plans and FROM/JOIN tables against these defs.
 *
 * Generated by scripts/generate-table-semantics.cjs — edit carefully or re-generate.
 */
import type { SemanticDef } from "@/query-agent/domain/semantics/types";

export const CUSTOMER_SEMANTICS: Readonly<Record<string, SemanticDef>> = {
  "count_customers": {
    "intent": "count_customers",
    "entity": "customer",
    "metric": "COUNT(*) or distinct count for count_customers",
    "grain": "scalar",
    "joins": [
      "customer",
      "individual",
      "contact",
      "salesorderheader",
      "salesorderdetail",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": []
  },
  "count_customers_by_type": {
    "intent": "count_customers_by_type",
    "entity": "customer",
    "metric": "COUNT(*) or distinct count for count_customers_by_type",
    "grain": "group_row",
    "joins": [
      "customer",
      "individual",
      "contact",
      "salesorderheader",
      "salesorderdetail",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "customerType"
    ]
  },
  "customers_by_type": {
    "intent": "customers_by_type",
    "entity": "customer",
    "metric": "customer attribute / spend listing",
    "grain": "customer",
    "joins": [
      "customer",
      "individual",
      "contact",
      "salesorderheader",
      "salesorderdetail",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "customerType"
    ]
  },
  "count_customers_by_territory": {
    "intent": "count_customers_by_territory",
    "entity": "customer",
    "metric": "COUNT(*) or distinct count for count_customers_by_territory",
    "grain": "group_row",
    "joins": [
      "customer",
      "individual",
      "contact",
      "salesorderheader",
      "salesorderdetail",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "territoryId"
    ]
  },
  "customers_by_territory": {
    "intent": "customers_by_territory",
    "entity": "customer",
    "metric": "customer attribute / spend listing",
    "grain": "customer",
    "joins": [
      "customer",
      "individual",
      "contact",
      "salesorderheader",
      "salesorderdetail",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "territoryId"
    ]
  },
  "customer_by_id": {
    "intent": "customer_by_id",
    "entity": "customer",
    "metric": "customer attribute / spend listing",
    "grain": "customer",
    "joins": [
      "customer",
      "individual",
      "contact",
      "salesorderheader",
      "salesorderdetail",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "customerId"
    ]
  },
  "customer_by_account": {
    "intent": "customer_by_account",
    "entity": "customer",
    "metric": "customer attribute / spend listing",
    "grain": "customer",
    "joins": [
      "customer",
      "individual",
      "contact",
      "salesorderheader",
      "salesorderdetail",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "accountNumber"
    ]
  },
  "list_customers": {
    "intent": "list_customers",
    "entity": "customer",
    "metric": "row listing for list_customers",
    "grain": "customer",
    "joins": [
      "customer",
      "individual",
      "contact",
      "salesorderheader",
      "salesorderdetail",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit"
    ]
  },
  "sample_customers": {
    "intent": "sample_customers",
    "entity": "customer",
    "metric": "row listing for sample_customers",
    "grain": "customer",
    "joins": [
      "customer",
      "individual",
      "contact",
      "salesorderheader",
      "salesorderdetail",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit"
    ]
  },
  "latest_customers": {
    "intent": "latest_customers",
    "entity": "customer",
    "metric": "row listing for latest_customers",
    "grain": "customer",
    "joins": [
      "customer",
      "individual",
      "contact",
      "salesorderheader",
      "salesorderdetail",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit"
    ]
  },
  "oldest_customers": {
    "intent": "oldest_customers",
    "entity": "customer",
    "metric": "row listing for oldest_customers",
    "grain": "customer",
    "joins": [
      "customer",
      "individual",
      "contact",
      "salesorderheader",
      "salesorderdetail",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit"
    ]
  },
  "count_customers_with_orders": {
    "intent": "count_customers_with_orders",
    "entity": "customer",
    "metric": "COUNT(*) or distinct count for count_customers_with_orders",
    "grain": "scalar",
    "joins": [
      "customer",
      "individual",
      "contact",
      "salesorderheader",
      "salesorderdetail",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": []
  },
  "count_customers_without_orders": {
    "intent": "count_customers_without_orders",
    "entity": "customer",
    "metric": "COUNT(*) or distinct count for count_customers_without_orders",
    "grain": "scalar",
    "joins": [
      "customer",
      "individual",
      "contact",
      "salesorderheader",
      "salesorderdetail",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": []
  },
  "pct_customers_with_orders": {
    "intent": "pct_customers_with_orders",
    "entity": "customer",
    "metric": "percentage for pct_customers_with_orders",
    "grain": "scalar",
    "joins": [
      "customer",
      "individual",
      "contact",
      "salesorderheader",
      "salesorderdetail",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": []
  },
  "list_customers_with_orders": {
    "intent": "list_customers_with_orders",
    "entity": "customer",
    "metric": "row listing for list_customers_with_orders",
    "grain": "customer",
    "joins": [
      "customer",
      "individual",
      "contact",
      "salesorderheader",
      "salesorderdetail",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit"
    ]
  },
  "list_customers_without_orders": {
    "intent": "list_customers_without_orders",
    "entity": "customer",
    "metric": "row listing for list_customers_without_orders",
    "grain": "customer",
    "joins": [
      "customer",
      "individual",
      "contact",
      "salesorderheader",
      "salesorderdetail",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit"
    ]
  },
  "top_customers_by_sales": {
    "intent": "top_customers_by_sales",
    "entity": "customer",
    "metric": "ranked list for top_customers_by_sales",
    "grain": "customer",
    "joins": [
      "customer",
      "individual",
      "contact",
      "salesorderheader",
      "salesorderdetail",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit"
    ]
  },
  "lowest_customers_by_sales": {
    "intent": "lowest_customers_by_sales",
    "entity": "customer",
    "metric": "ranked list for lowest_customers_by_sales",
    "grain": "customer",
    "joins": [
      "customer",
      "individual",
      "contact",
      "salesorderheader",
      "salesorderdetail",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit"
    ]
  },
  "top_customers_by_order_count": {
    "intent": "top_customers_by_order_count",
    "entity": "customer",
    "metric": "ranked list for top_customers_by_order_count",
    "grain": "customer",
    "joins": [
      "customer",
      "individual",
      "contact",
      "salesorderheader",
      "salesorderdetail",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit"
    ]
  },
  "lowest_customers_by_order_count": {
    "intent": "lowest_customers_by_order_count",
    "entity": "customer",
    "metric": "ranked list for lowest_customers_by_order_count",
    "grain": "customer",
    "joins": [
      "customer",
      "individual",
      "contact",
      "salesorderheader",
      "salesorderdetail",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit"
    ]
  },
  "customers_by_category_spend": {
    "intent": "customers_by_category_spend",
    "entity": "customer",
    "metric": "customer attribute / spend listing",
    "grain": "customer",
    "joins": [
      "customer",
      "individual",
      "contact",
      "salesorderheader",
      "salesorderdetail",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "category"
    ]
  },
  "avg_customer_spend": {
    "intent": "avg_customer_spend",
    "entity": "customer",
    "metric": "AVG(...) for avg_customer_spend",
    "grain": "scalar",
    "joins": [
      "customer",
      "individual",
      "contact",
      "salesorderheader",
      "salesorderdetail",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": []
  },
  "median_customer_spend": {
    "intent": "median_customer_spend",
    "entity": "customer",
    "metric": "median aggregate for median_customer_spend",
    "grain": "scalar",
    "joins": [
      "customer",
      "individual",
      "contact",
      "salesorderheader",
      "salesorderdetail",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": []
  },
  "sum_customer_spend": {
    "intent": "sum_customer_spend",
    "entity": "customer",
    "metric": "SUM(...) for sum_customer_spend",
    "grain": "scalar",
    "joins": [
      "customer",
      "individual",
      "contact",
      "salesorderheader",
      "salesorderdetail",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": []
  },
  "max_customer_spend": {
    "intent": "max_customer_spend",
    "entity": "customer",
    "metric": "MAX(...) for max_customer_spend",
    "grain": "scalar",
    "joins": [
      "customer",
      "individual",
      "contact",
      "salesorderheader",
      "salesorderdetail",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": []
  },
  "min_customer_spend": {
    "intent": "min_customer_spend",
    "entity": "customer",
    "metric": "MIN(...) for min_customer_spend",
    "grain": "scalar",
    "joins": [
      "customer",
      "individual",
      "contact",
      "salesorderheader",
      "salesorderdetail",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": []
  },
  "avg_orders_per_customer": {
    "intent": "avg_orders_per_customer",
    "entity": "customer",
    "metric": "AVG(...) for avg_orders_per_customer",
    "grain": "group_row",
    "joins": [
      "customer",
      "individual",
      "contact",
      "salesorderheader",
      "salesorderdetail",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": []
  },
  "customer_spend_for_id": {
    "intent": "customer_spend_for_id",
    "entity": "customer",
    "metric": "customer attribute / spend listing",
    "grain": "customer",
    "joins": [
      "customer",
      "individual",
      "contact",
      "salesorderheader",
      "salesorderdetail",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "customerId"
    ]
  },
  "customer_order_count_for_id": {
    "intent": "customer_order_count_for_id",
    "entity": "customer",
    "metric": "customer attribute / spend listing",
    "grain": "customer",
    "joins": [
      "customer",
      "individual",
      "contact",
      "salesorderheader",
      "salesorderdetail",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "customerId"
    ]
  },
  "customers_spend_over": {
    "intent": "customers_spend_over",
    "entity": "customer",
    "metric": "customer attribute / spend listing",
    "grain": "customer",
    "joins": [
      "customer",
      "individual",
      "contact",
      "salesorderheader",
      "salesorderdetail",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "minSpend"
    ]
  },
  "customers_spend_under": {
    "intent": "customers_spend_under",
    "entity": "customer",
    "metric": "customer attribute / spend listing",
    "grain": "customer",
    "joins": [
      "customer",
      "individual",
      "contact",
      "salesorderheader",
      "salesorderdetail",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "maxSpend"
    ]
  },
  "customers_with_min_orders": {
    "intent": "customers_with_min_orders",
    "entity": "customer",
    "metric": "customer attribute / spend listing",
    "grain": "customer",
    "joins": [
      "customer",
      "individual",
      "contact",
      "salesorderheader",
      "salesorderdetail",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "minOrders"
    ]
  },
  "top_customers_by_sales_period": {
    "intent": "top_customers_by_sales_period",
    "entity": "customer",
    "metric": "ranked list for top_customers_by_sales_period",
    "grain": "customer",
    "joins": [
      "customer",
      "individual",
      "contact",
      "salesorderheader",
      "salesorderdetail",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "timeField": "salesorderheader.OrderDate",
    "filtersAllowed": [
      "limit",
      "lastMonths",
      "lastDays"
    ]
  },
  "top_customers_by_sales_type": {
    "intent": "top_customers_by_sales_type",
    "entity": "customer",
    "metric": "ranked list for top_customers_by_sales_type",
    "grain": "customer",
    "joins": [
      "customer",
      "individual",
      "contact",
      "salesorderheader",
      "salesorderdetail",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit",
      "customerType"
    ]
  },
  "top_customers_by_sales_territory": {
    "intent": "top_customers_by_sales_territory",
    "entity": "customer",
    "metric": "ranked list for top_customers_by_sales_territory",
    "grain": "customer",
    "joins": [
      "customer",
      "individual",
      "contact",
      "salesorderheader",
      "salesorderdetail",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit",
      "territoryId"
    ]
  },
  "avg_spend_by_type": {
    "intent": "avg_spend_by_type",
    "entity": "customer",
    "metric": "AVG(...) for avg_spend_by_type",
    "grain": "group_row",
    "joins": [
      "customer",
      "individual",
      "contact",
      "salesorderheader",
      "salesorderdetail",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "customerType"
    ]
  },
  "avg_spend_by_territory": {
    "intent": "avg_spend_by_territory",
    "entity": "customer",
    "metric": "AVG(...) for avg_spend_by_territory",
    "grain": "group_row",
    "joins": [
      "customer",
      "individual",
      "contact",
      "salesorderheader",
      "salesorderdetail",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "territoryId"
    ]
  },
  "customer_count_by_territory_type": {
    "intent": "customer_count_by_territory_type",
    "entity": "customer",
    "metric": "customer attribute / spend listing",
    "grain": "customer",
    "joins": [
      "customer",
      "individual",
      "contact",
      "salesorderheader",
      "salesorderdetail",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "territoryId",
      "customerType"
    ]
  },
  "compare_customer_types_spend": {
    "intent": "compare_customer_types_spend",
    "entity": "customer",
    "metric": "customer attribute / spend listing",
    "grain": "customer",
    "joins": [
      "customer",
      "individual",
      "contact",
      "salesorderheader",
      "salesorderdetail",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "customerType"
    ]
  },
  "pct_customers_by_type": {
    "intent": "pct_customers_by_type",
    "entity": "customer",
    "metric": "percentage for pct_customers_by_type",
    "grain": "group_row",
    "joins": [
      "customer",
      "individual",
      "contact",
      "salesorderheader",
      "salesorderdetail",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "customerType"
    ]
  },
  "variance_customer_spend": {
    "intent": "variance_customer_spend",
    "entity": "customer",
    "metric": "VARIANCE(...) for variance_customer_spend",
    "grain": "scalar",
    "joins": [
      "customer",
      "individual",
      "contact",
      "salesorderheader",
      "salesorderdetail",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": []
  },
  "customers_modified_after": {
    "intent": "customers_modified_after",
    "entity": "customer",
    "metric": "customer attribute / spend listing",
    "grain": "customer",
    "joins": [
      "customer",
      "individual",
      "contact",
      "salesorderheader",
      "salesorderdetail",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "timeField": "customer.ModifiedDate",
    "filtersAllowed": [
      "year",
      "years",
      "startYear",
      "endYear",
      "sellStartYear"
    ]
  },
  "count_store_customers": {
    "intent": "count_store_customers",
    "entity": "customer",
    "metric": "COUNT(*) or distinct count for count_store_customers",
    "grain": "scalar",
    "joins": [
      "customer",
      "individual",
      "contact",
      "salesorderheader",
      "salesorderdetail",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "customerType"
    ]
  },
  "count_individual_customers": {
    "intent": "count_individual_customers",
    "entity": "customer",
    "metric": "COUNT(*) or distinct count for count_individual_customers",
    "grain": "scalar",
    "joins": [
      "customer",
      "individual",
      "contact",
      "salesorderheader",
      "salesorderdetail",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "customerType"
    ]
  },
  "random_sample_store_customers": {
    "intent": "random_sample_store_customers",
    "entity": "customer",
    "metric": "customer attribute / spend listing",
    "grain": "customer",
    "joins": [
      "customer",
      "individual",
      "contact",
      "salesorderheader",
      "salesorderdetail",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit",
      "customerType"
    ]
  },
  "top_account_numbers_by_sales": {
    "intent": "top_account_numbers_by_sales",
    "entity": "customer",
    "metric": "ranked list for top_account_numbers_by_sales",
    "grain": "customer",
    "joins": [
      "customer",
      "individual",
      "contact",
      "salesorderheader",
      "salesorderdetail",
      "product",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "limit",
      "accountNumber"
    ]
  },
  "customers_by_name": {
    "intent": "customers_by_name",
    "entity": "customer",
    "metric": "customer attribute / spend listing",
    "grain": "customer",
    "joins": [
      "customer",
      "individual",
      "contact"
    ],
    "filtersAllowed": [
      "nameContains",
      "firstName",
      "lastName",
      "email",
      "phone",
      "limit"
    ]
  },
  "count_customers_by_name": {
    "intent": "count_customers_by_name",
    "entity": "customer",
    "metric": "COUNT(*) or distinct count for count_customers_by_name",
    "grain": "group_row",
    "joins": [
      "customer",
      "individual",
      "contact"
    ],
    "filtersAllowed": [
      "nameContains",
      "firstName",
      "lastName",
      "email",
      "phone",
      "limit"
    ]
  },
  "orders_for_customers_by_name": {
    "intent": "orders_for_customers_by_name",
    "entity": "customer",
    "metric": "Order list (TotalDue) for customers matching contact name/email/phone",
    "grain": "order",
    "joins": [
      "customer",
      "individual",
      "contact",
      "salesorderheader"
    ],
    "filtersAllowed": [
      "nameContains",
      "firstName",
      "lastName",
      "email",
      "phone",
      "lastMonths",
      "limit"
    ],
    "timeField": "salesorderheader.OrderDate"
  }
} as const;
