/**
 * semantics.ts — mixed semantic layer (metric / grain / joins / filters).
 * Traceability for intents in this module. SQL templates remain in sql.ts;
 * the registry validates plans and FROM/JOIN tables against these defs.
 *
 * Generated by scripts/generate-table-semantics.cjs — edit carefully or re-generate.
 */
import type { SemanticDef } from "@/query-agent/domain/semantics/types";

export const MIXED_SEMANTICS: Readonly<Record<string, SemanticDef>> = {
  "products_sold_to_named_customers": {
    "intent": "products_sold_to_named_customers",
    "entity": "mixed",
    "metric": "Line items: product sold to named customer (LineTotal / OrderQty)",
    "grain": "order_line",
    "joins": [
      "product",
      "salesorderdetail",
      "salesorderheader",
      "customer",
      "individual",
      "contact",
      "productsubcategory",
      "productcategory"
    ],
    "filtersAllowed": [
      "productNameContains",
      "customerNameContains",
      "lastMonths",
      "category",
      "limit"
    ],
    "timeField": "salesorderheader.OrderDate",
    "notes": "Cross-table seed: product → detail → header → customer → individual → contact"
  }
} as const;
